package domain;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

/**
 * beim user könnte man vll auch die info festlegen, ob jemand cheated oder nicht*/

public class User {
    private String name;
    private UUID id;
    private double points;

    private static Map<String, UUID> preventDuplicates = new HashMap<>();

    public User(String name) {
        if (preventDuplicates.containsKey(name)) {
            throw new IllegalArgumentException("name already exists");
        }
        this.name = name;
        this.id = UUID.randomUUID();
        this.points = 0;
        //add name to Map
        preventDuplicates.put(name, id);
    }

    //autogenerated getters and setters
    public String getName() {
        return name;
    }

    public void setName(String name) {
        if (preventDuplicates.containsKey(name)) {
            throw new IllegalArgumentException("name already exists");
        }
        this.name = name;
    }

    public UUID getId() {
        return id;
    }

    /*public void setId(UUID id) {
        this.id = id;
    }*/
    //cause it is autogenerated

    public double getPoints() {
        return points;
    }

    public void setPoints(double points) {
        this.points = points;
    }
}
